-- Navigate vim panes better
vim.keymap.set('n', '<c-k>', ':wincmd k<CR>')
vim.keymap.set('n', '<c-j>', ':wincmd j<CR>')
vim.keymap.set('n', '<c-h>', ':wincmd h<CR>')
vim.keymap.set('n', '<c-l>', ':wincmd l<CR>')
vim.keymap.set('n', '<leader>h', ':nohlsearch<CR>')
vim.api.nvim_set_keymap('n', '<C-a>', 'ggVG', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<C-c>', '"+y', { noremap = true, silent = true })
vim.keymap.set("n", "<leader>F", function()
  require("conform").format()
end, { desc = "Manual format current buffer" })
vim.keymap.set("v", "<leader>rf", function()
  require("conform").format({ range = true })
end, { desc = "Format selected range" })
vim.keymap.set("n", "<F3>", function()
  require("conform").format()
end, { desc = "Format current buffer with F3" })

-- Keybinding for Telescope
vim.api.nvim_set_keymap('n', '<C-f>', ':Telescope find_files<CR>', { noremap = true, silent = true })
